dist: trusty
sudo: required

language: node_js
node_js:
  - '16'

addons:
  chrome: stable
cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - nx run-many --all --target=test
